c script-binding select/select-chapter
MBTN_LEFT no-osd set speed 2; set pause no    #@press
MBTN_LEFT       ignore                        #@release
F1 af toggle "lavfi=[loudnorm]" ; show-text "${af}"
F2 af toggle "lavfi=[dynaudnorm]"; show-text "${af}"
Ctrl+Shift+l cycle-values loop-playlist inf no
