# https://mpv.io/manual/master/

# --flag => flag
# -opt val => opt=val
# --opt=val => opt=val
# -opt "has spaces" => opt=has spaces

hwdec=auto

force-window=yes

# using mpv thumnail script
osc=no

# inputevent.lua
input-doubleclick-time=200

# turn off unicode font warnings
msg-level=osd/libass=no

