splash = false

wallpaper {
    monitor = DP-3
    path = ~/Pictures/wallpapers/ado_13117125.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-4
    path = ~/Pictures/wallpapers/ado_13117125_crop.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-5
    path = ~/Pictures/wallpapers/ado_13117125.jpg
    fit_mode = cover
}
